---

- name: Set hostnames
  import_tasks: set-hostnames.yml

- name: Bootstrap the global Vault
  import_tasks: global-vault-bootstrap.yml

- name: Assemble consul cluster
  import_role:
    name: ansible-consul

- name: Assemble vault cluster
  import_role:
    name: ansible-vault

- name: Initialize the global Vault
  import_tasks: vault-init.yml

- name: Create and retrieve nomad-server policy token
  import_tasks: create-nomad-token.yml

- name: Assemble nomad cluster
  import_role:
    name: ansible-nomad

- name: Create and retrieve nomad-server policy token
  import_tasks: configure-consul-template.yml