---

- name: Create ca_certificate dir
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/local
    state: directory

- name: Write root ca file to dir
  copy:
    content: "{{ root_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_root_ca.crt
    force: true

- name: Write consul ca file to dir
  copy:
    content: "{{ consul_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_consul_ca.crt
    force: true

- name: Write nomad ca file to dir
  copy:
    content: "{{ nomad_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_nomad_ca.crt
    force: true

- name: Write vault ca file to dir
  copy:
    content: "{{ vault_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_vault_ca.crt
    force: true

- name: Create ca_certificate local dir
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/local
    state: directory
  run_once: yes
  delegate_to: localhost

- name: Write root ca file to local dir
  copy:
    content: "{{ root_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_root_ca.crt
    force: true
  run_once: yes
  delegate_to: localhost

- name: Write consul ca file to local dir
  copy:
    content: "{{ consul_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_consul_ca.crt
    force: true
  run_once: yes
  delegate_to: localhost

- name: Write nomad ca file to local dir
  copy:
    content: "{{ nomad_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_nomad_ca.crt
    force: true
  run_once: yes
  delegate_to: localhost

- name: Write vault ca file to local dir
  copy:
    content: "{{ vault_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_vault_ca.crt
    force: true
  run_once: yes
  delegate_to: localhost

- name: dpkg-reconfigure ca-certificate
  command: update-ca-certificates
  become: yes

- name: dpkg-reconfigure ca-certificate local
  local_action: command update-ca-certificates
  become: yes