variables:
  VAULT_VERSION: "1.11.1"
  VAULT_ADDR: "https://vault-cluster-public-vault-7dc00120.aa9a44f3.z1.hashicorp.cloud:8200/"
  VAULT_NAMESPACE: admin

stages:
  - run


run:
  stage: run
  image: 
    name: registry.gitlab.com/p8811/raspberry-arm-image/docker-ansible:main
  script:
    - ansible-galaxy install "git+https://github.com/Deltamir/ansible-consul.git,Deltamir-patch-1" --force
    - mv $ID_RSA id_rsa
    - chmod 400 id_rsa 
    - ssh-keygen -p -m PEM -f id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook playbook-test.yml -i inventory
  tags:
    - paquerettes
