variables:
  - VAULT_VERSION: "1.11.1"

stages:
  - run


run:
  stage: run
  image: 
    name: registry.gitlab.com/p8811/raspberry-arm-image/docker-ansible:main
  script:
    - apt-get update -qqy
    - apt-get install -qqy unzip
    - echo $ID_RSA
    - mv $ID_RSA id_rsa
    - cat id_rsa
    - chmod 400 id_rsa 
    - ssh-keygen -p -m PEM -f id_rsa
    - cat id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - apt-get update -qqy
    - apt-get install sshpass -qqy
    - ansible-playbook playbook.yml -i inventory
  tags:
    - raspberry
