variables:
  VAULT_VERSION: "1.11.1"
  VAULT_INIT_ARM_VERSION: "1.0.1"

stages:
  - run


run:
  stage: run
  image: 
    name: registry.gitlab.com/p8811/raspberry-arm-image/docker-ansible:main
  script:
    - apt-get update -qqy
    - apt-get install curl -qqy
    - |
      curl --header "PRIVATE-TOKEN: ${PRIVATE_TOKEN}"  ${CI_API_V4_URL}/projects/38045196/packages/generic/vault-init-aws/${VAULT_INIT_ARM_VERSION}/vault-init-aws_arm32v7_${VAULT_INIT_ARM_VERSION} -o vault-init
    - pip install ansible-modules-hashivault
    - mv $ID_RSA id_rsa
    - chmod 400 id_rsa 
    - ssh-keygen -p -m PEM -f id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook playbook.yml -i inventory
  tags:
    - paquerettes
