variables:
  VAULT_VERSION: "1.11.1"

stages:
  - run


run:
  stage: run
  image: 
    name: registry.gitlab.com/p8811/raspberry-arm-image/docker-ansible:main
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - mv $ID_RSA id_rsa
    - chmod 400 id_rsa 
    - ssh-keygen -p -m PEM -f id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook playbook.yml -i inventory
  tags:
    - paquerettes
