
stages:
  - run


run:
  stage: run
  image: 
    name: arm32v7/debian
  script:
    - apt-get update -qqy 
    - apt-get install -qqy --no-install-recommends python3 python3-pip git ansible
    - rm -rf /var/lib/apt/lists/* \
    - ansible-galaxy install git+https://github.com/ansible-community/ansible-vault.git
    - echo $ID_RSA > id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - apt-get update -qqy
    - apt-get install sshpass -qqy
    - ansible-playbook playbook.yml -i inventory
  tags:
    - raspberry
