variables:
  VAULT_VERSION: "1.11.1"
  VAULT_ADDR: "https://vault-cluster-public-vault-69dbd168.2abff579.z1.hashicorp.cloud:8200/"
  VAULT_NAMESPACE: admin

stages:
  - run


run:
  stage: run
  image: 
    name: registry.gitlab.com/p8811/raspberry-arm-image/docker-ansible:main
  script:
    - apt-get update -qqy
    - apt-get install dnsutils --qqy
    - dig vault.service.consul
    - dig vault.service.consul 192.168.1.40
    - ansible-galaxy install "git+https://github.com/Deltamir/ansible-consul.git,Deltamir-patch-1" --force
    - mv $ID_RSA id_rsa
    - chmod 400 id_rsa 
    - ssh-keygen -p -m PEM -f id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook playbook.yml -i inventory2
  tags:
    - paquerettes
