variables:
  VAULT_VERSION: "1.11.1"
  VAULT_INIT_ARM_VERSION: "1.0.0"

stages:
  - run


run:
  stage: run
  image: 
    name: registry.gitlab.com/p8811/raspberry-arm-image/docker-ansible:main
  script:
    - curl https://gitlab.com/p8811/raspberry-arm-image/vault-init-arm/-/package_files/47140545/download
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}"  ${CI_API_V4_URL}/projects/38045196/packages/generic/vault-init-aws/${VAULT_INIT_ARM_VERSION}/vault-init-aws_arm32v7_${VAULT_INIT_ARM_VERSION} -o vault-init
    - ls
    - mv $ID_RSA id_rsa
    - chmod 400 id_rsa 
    - ssh-keygen -p -m PEM -f id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook playbook.yml -i inventory
  tags:
    - paquerettes
