---
variables:
  DEBIAN_BUILD_IMAGE: arm32v7/debian:11.6
  ANSIBLE_IMAGE: cytopia/ansible:2.13-tools
  ANSIBLE_LINT_IMAGE: haxorof/ansible-lint:v6
  GITLEAKS_IMAGE: zricethezav/gitleaks:v8.15.3
  PUSHRM_CI_IMAGE: chko/docker-pushrm:1.9.0
  YQ_CI_IMAGE: mikefarah/yq:4.30.8
  ANSIBLE_VERSION: 2.10.7+merged+base+2.10.8+dfsg-1
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_REQUIREMENTS_FILE: "requirements.yml"
  GITLEAKS_ARGS: "--verbose"
  REGISTRY_IMAGE: "${DOCKER_REGISTRY_USER}/${CI_PROJECT_NAME}"
  ANSIBLE_ROLE: "${DOCKER_REGISTRY_USER}/ansible_hashistack"
  GIT_AUTHOR_EMAIL: "math.germain.54@gmail.com"
  GIT_COMMITTER_EMAIL: "math.germain.54@gmail.com"
  SEMREL_CHANGELOG_ENABLED: 'true'
  SEMREL_AUTO_RELEASE_ENABLED: 'true'
  SEMREL_INFO_ON: 'protected'
  AUTODEPLOY_TO_PROD: 'true'
  DOCKER_RELEASE_IMAGE: "docker.io/$REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  DOCKER_SNAPSHOT_IMAGE: "docker.io/$REGISTRY_IMAGE:snapshot-$CI_COMMIT_REF_SLUG"
  DOCKER_KANIKO_VERBOSITY: "trace"

stages:
  - test
  - build
  - package-build
  - package-test
  - publish

include:
  - project: 'to-be-continuous/semantic-release'
    ref: '3.2.1'
    file: '/templates/gitlab-ci-semrel.yml'
  - project: 'to-be-continuous/docker'
    ref: '3.5.2'
    file: '/templates/gitlab-ci-docker.yml'

ansible-lint:
  stage: test
  image:
    name: $ANSIBLE_LINT_IMAGE
    entrypoint: [""]
  script:
    - ansible-lint handlers/*.yml -w no-handler -w no-changed-when
    - ansible-lint tasks/*.yml -w no-handler -w no-changed-when
    - ansible-lint vars/*.yml -w no-handler -w no-changed-when
  tags:
    - vps

gitleaks:
  stage: test
  image:
    name: $GITLEAKS_IMAGE
    entrypoint: [ "" ]
  variables:
    GIT_DEPTH: 0
  before_script:
    - mkdir -p ./gitleaks
  script:
    - gitleaks detect --source . --report-path ./gitleaks/gitleaks-report.json $GITLEAKS_ARGS
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - gitleaks/
  tags:
    - vps

docker-hadolint:
  stage: test

docker-kaniko-build:
  script:
    - cat /kaniko/.docker/config.json
    - run_build_kaniko "$DOCKER_SNAPSHOT_IMAGE" --digest-file .img-digest.txt --build-arg http_proxy="$http_proxy" --build-arg https_proxy="$https_proxy" --build-arg no_proxy="$no_proxy"
    # push docker_image in dotenv file
    - docker_digest=$(cat .img-digest.txt)
    - docker_repository=${DOCKER_SNAPSHOT_IMAGE%:*}
    - docker_tag=${DOCKER_SNAPSHOT_IMAGE##*:}
    - echo "docker_image=$DOCKER_SNAPSHOT_IMAGE" > docker.env
    - echo "docker_image_digest=$docker_repository@$docker_digest" >> docker.env
    - echo "docker_repository=$docker_repository" >> docker.env
    - echo "docker_tag=$docker_tag" >> docker.env
    - echo "docker_digest=$docker_digest" >> docker.env


galaxy-read-description:
  stage: build
  image:
    name: $YQ_CI_IMAGE
    entrypoint: [ "" ]
  script:
    - JOB_DESCRIPTION=$(yq .galaxy_info.description < meta/main.yml)
    - echo $JOB_DESCRIPTION
    - echo "JOB_DESCRIPTION=$JOB_DESCRIPTION" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

docker-sbom:
  artifacts:
    name: "SBOM for docker from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 1 week
    when: always
    paths:
      - "reports/docker-sbom-*.cyclonedx.json"
    reports:
      cyclonedx:
        - "reports/docker-sbom-*.cyclonedx.json"


galaxy-import:
  stage: publish
  image: $ANSIBLE_IMAGE
  script:
    - ansible-galaxy role import $GITHUB_USER $GITHUB_REPO --token $ANSIBLE_GALAXY
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - vps


docker-pushrm:
  stage: publish
  image:
    name: $PUSHRM_CI_IMAGE
    entrypoint: ["/bin/sh", "-c", "/docker-pushrm"]
  variables:
    DOCKER_USER: $REGISTRY_USER
    DOCKER_PASS: $REGISTRY_PASSWORD
    PUSHRM_SHORT: $JOB_DESCRIPTION
    PUSHRM_TARGET: $REGISTRY_IMAGE
    PUSHRM_DEBUG: 1
    PUSHRM_FILE: $CI_PROJECT_DIR/README-dockerhub.md
  script: "/bin/true"
  tags:
    - vps
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

