---
variables:
  # Docker Image with Ansible
  ANSIBLE_IMAGE: "cytopia/ansible:latest-tools"
  ANSIBLE_BASE_APP_NAME: "$CI_PROJECT_NAME"
  ANSIBLE_PROJECT_DIR: "."
  ANSIBLE_LINT_IMAGE: "haxorof/ansible-lint:latest"
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_REQUIREMENTS_FILE: "requirements.yml"
  GITLEAKS_IMAGE: "registry.hub.docker.com/zricethezav/gitleaks:latest"
  GITLEAKS_ARGS: "--verbose"
  ANSIBLE_VAULT_VERSION: 2022.12.01
  ANSIBLE_CONSUL_VERSION: v3.0.1
  ANSIBLE_NOMAD_VERSION: v1.9.6


stages:
  - test

ansible-lint:
  stage: test
  image:
    name: "$ANSIBLE_LINT_IMAGE"
    entrypoint: [""]
  script:
    - ansible-lint handlers/*.yml -w no-handler -w no-changed-when
    - ansible-lint tasks/*.yml -w no-handler -w no-changed-when
    - ansible-lint vars/*.yml -w no-handler -w no-changed-when

gitleaks:
  stage: test
  image:
    name: $GITLEAKS_IMAGE
    entrypoint: [ "" ]
  variables:
    GIT_DEPTH: 0
  before_script:
    - mkdir -p ./gitleaks
  script:
    - gitleaks detect --source . --report-path ./gitleaks/gitleaks-report.json $GITLEAKS_ARGS
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - gitleaks/

