- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
          - hvac
      become: true

    - name: enable kv-v1 secret engine
      hashivault_secret_engine:
        name: kv
        url: "https://vault-cluster-public-vault-69dbd168.2abff579.z1.hashicorp.cloud:8200/"
        state: enabled
        authtype: token
        verify: no
        namespace: "admin"

    - name: retrieve Consul Gossip key from HCP
      set_fact:
        consul_gossip_key: "{{ lookup('community.hashi_vault.vault_kv1_get', 'consul_gossip_key') }}"
      ignore_errors: yes
      register: consul_failure

    - name: Generate a consul encyption key
      local_action:
        module: command
        cmd: openssl rand -base64 32
      register: encryption_key
      when: consul_failure['failed'] == true

    - name: write consul gossip encryption key to vault
      hashivault_secret:
        secret: "consul_gossip_key"
        data:
          key: "{{ encryption_key.stdout }}"
        verify: no
        version: 1
        mount_point: "kv"
      when: consul_failure['failed'] == true

    - name: Register Consul Gossip key
      set_fact:
        consul_gossip_key:  "{{ encryption_key.stdout }}" 
      when: consul_failure['failed'] == true

    - name: Register Consul Gossip key
      set_fact:
        consul_gossip_key:  "{{ consul_gossip_key.data.key }}"
      when: consul_failure['failed'] == false
    
    - debug:
        msg: "{{ consul_gossip_key }}"
