- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
          - hvac
      become: true

    - name: Authenticate with JWT against HCP
      community.hashi_vault.vault_login:
        auth_method: jwt
        jwt: "{{ lookup('env', 'CI_JOB_JWT') }}"
        role_id: gitlab-jwt
        mount_point: gitlab-jwt
      register: hcp_vault_token
    
    - debug:
        msg: "{{ hcp_vault_token }}"

    - debug:
        msg: "{{ hcp_vault_token.login.auth.client_token }}"

    - debug:
        msg: "{{ lookup('env', 'VAULT_TOKEN') }}"
      environment:
        VAULT_TOKEN: '{{ hcp_vault_token.login.auth.client_token }}'

    - name: Set fact for JWT
      set_fact:
        hcp_vault_token: "{{ hcp_vault_token.login.auth.client_token }}"

    - debug:
        msg: "{{ hcp_vault_token }}"

    - debug:
        msg: "{{ lookup('env', 'VAULT_TOKEN') }}"
      environment:
        VAULT_TOKEN: "{{ hcp_vault_token }}"

- hosts: localhost
  environment:
    VAULT_TOKEN: "{{ hcp_vault_token }}"
  tasks:
    - debug:
        msg: "{{ lookup('env', 'VAULT_TOKEN') }}"

    - name: enable kv-v1 secret engine on HCP
      hashivault_secret_engine:
        name: kv
        state: enabled

    - name: 
      set_fact:
        consul_gossip_key: "{{ lookup('community.hashi_vault.vault_kv1_get', 'consul_gossip_key') }}"
      ignore_errors: yes
      register: consul_failure

    - name: Generate a consul encyption key
      local_action:
        module: command
        cmd: openssl rand -base64 32
      register: encryption_key
      when: consul_failure['failed'] == true

    - name: write consul gossip encryption key to HCP
      hashivault_secret:
        secret: "consul_gossip_key"
        data:
          key: "{{ encryption_key.stdout }}"
        verify: no
        version: 1
        mount_point: "kv"
      when: consul_failure['failed'] == true

    - name: Register Consul Gossip key if necessary
      set_fact:
        consul_gossip_key:  "{{ encryption_key.stdout }}" 
      when: consul_failure['failed'] == true

    - name: Register Consul Gossip key if necessary
      set_fact:
        consul_gossip_key:  "{{ consul_gossip_key.data.key }}" 
      when: consul_failure['failed'] == false

    - name: retrieve Nomad Gossip key from HCP
      set_fact:
        nomad_gossip_key: "{{ lookup('community.hashi_vault.vault_kv1_get', 'nomad_gossip_key') }}"
      ignore_errors: yes
      register: nomad_failure

    - name: Generate a nomad encyption key
      local_action:
        module: command
        cmd: openssl rand -base64 32
      register: encryption_key
      when: nomad_failure['failed'] == true

    - name: write nomad gossip encryption key to HCP
      hashivault_secret:
        secret: "nomad_gossip_key"
        data:
          key: "{{ encryption_key.stdout }}"
        verify: no
        version: 1
        mount_point: "kv"
      when: nomad_failure['failed'] == true

    - name: Register Nomad Gossip key if necessary
      set_fact:
        nomad_gossip_key:  "{{ encryption_key.stdout }}" 
      when: nomad_failure['failed'] == true

    - name: Register Nomad Gossip key if necessary
      set_fact:
        nomad_gossip_key:  "{{ nomad_gossip_key.data.key }}"
      when: nomad_failure['failed'] == false

    - name: enable transit secret engine on GCP
      hashivault_secret_engine:
        name: transit
        state: enabled
        
    - name: create autounseal secret on HCP
      community.hashi_vault.vault_write:
        path: transit/keys/autounseal
      register: test

    - name: Create autounseal policy on HCP
      hashivault_policy:
        name: autounseal
        rules_file : autounseal.hcl 

    - name: Create a autounseal token from HCP
      community.hashi_vault.vault_token_create:
      register: "autounseal_token"  

- name: Assemble Consul cluster
  hosts: consul_instances
  vars:
    consul_raw_key: "{{ hostvars['localhost'].consul_gossip_key }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-consul}

- hosts: vault_instances
  vars:
    autounseal_token: "{{ hostvars['localhost'].autounseal_token.login.auth.client_token }}"
  tasks:
    - name: Ensures vault config dir exists
      file: 
        path: /etc/vault.d/
        state: directory
      become: true

    - name: Copy vault seal config script 
      template:
        src: vault_seal.j2
        dest: /etc/vault.d/vault_seal.hcl
      become: true

- name: Install Vault cluster
  hosts: vault_instances
  vars:
    vault_awskms_key_id: "{{ hostvars['localhost'].kms_key.key_arn }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-vault}

- hosts: localhost
  environment:
    VAULT_TOKEN: "{{ hcp_vault_token.login.auth.client_token }}"
  tasks:
    - name: init Vault
      hashivault_init:
        recovery_shares: 1
        recovery_threshold: 1
        url: "http://{{ groups['vault_instances'][0] }}:8200"
      register: vault_init
      run_once: yes

    - name: Write root token to HCP
      hashivault_secret:
        secret: "vault_root_token"
        data:
          key: "{{ vault_init.root_token }}"
        verify: no
        version: 1
        mount_point: "kv"
      when: vault_init['changed'] == true

    - name: retrieve root token from HCP
      set_fact:
        root_token: "{{ lookup('community.hashi_vault.vault_kv1_get', 'vault_root_token') }}"
      ignore_errors: yes

    - name: Sleep for 30s if vault was not initialized
      ansible.builtin.wait_for:
        timeout: 30
      when: vault_init['changed'] == true

    - name: Create nomad-server policy on local vault
      hashivault_policy:
        token: "{{ root_token.data.key }}"
        name: nomad-server
        rules_file : nomad-server-policy.hcl
        url: "http://vault.service.consul:8200"

    - name: create nomad-cluster token role on local vault
      community.hashi_vault.vault_write:
        token: "{{ root_token.data.key }}"
        url: http://vault.service.consul:8200
        path: auth/token/roles/nomad-cluster
        data: "{{ lookup('file','nomad-cluster-role.json') | from_json }}"

    - name: Create a nomad token from local vault
      community.hashi_vault.vault_token_create:
        url: http://vault.service.consul:8200
        policies: ["nomad-server"]
        orphan: true
        period: "72h"
        token: "{{ root_token.data.key }}"
      register: "nomad_vault_token"

- name: Installing Nomad
  hosts: nomad_instances
  vars:
    nomad_vault_token: "{{ hostvars['localhost'].nomad_vault_token.login.auth.client_token }}"
    nomad_encrypt: "{{ hostvars['localhost'].nomad_gossip_key }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-nomad}
