- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
          - hvac
      become: true

    - name: enable kv-v1 secret engine
      hashivault_secret_engine:
        name: kv
        url: "https://vault-cluster-public-vault-69dbd168.2abff579.z1.hashicorp.cloud:8200/"
        state: enabled
        authtype: token
        verify: no
        namespace: "admin"

    - name: retrieve Consul Gossip key from AWS Secrets Manager
      set_fact:
        consul_gossip_key: "{{ lookup('community.hashi_vault.vault_kv1_get', 'consul_gossip_key') }}"
      ignore_error: yes
      register: consul_failure

    - debug:
        msg: "{{ consul_failure }}"

    - debug:
        msg: "{{ consul_gossip_key }}"
