- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
          - hvac
      become: true

    - name: enable transit secret engine
      hashivault_secret_engine:
        name: transit
        url: "https://vault-cluster-public-vault-69dbd168.2abff579.z1.hashicorp.cloud:8200/"
        state: enabled
        authtype: token
        verify: no
        namespace: "admin"
        
    - name: create autounseal secret
      community.hashi_vault.vault_write:
        url: http://vault.service.consul:8200
        path: transit/keys/autounseal
