- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
          - hvac
      become: true

    - name: enable kv-v1 secret engine
      hashivault_secret_engine:
        name: kv
        url: "https://vault-cluster-public-vault-69dbd168.2abff579.z1.hashicorp.cloud:8200/"
        state: enabled
        authtype: token
        verify: no
        namespace: "admin"

    - name: retrieve Consul Gossip key from HCP
      set_fact:
        consul_gossip_key: "{{ lookup('community.hashi_vault.vault_kv1_get', 'consul_gossip_key') }}"
      ignore_errors: yes
      register: consul_failure

    - name: Generate a consul encyption key
      local_action:
        module: command
        cmd: openssl rand -base64 32
      register: encryption_key
      when: consul_failure['failed'] == true

    - name: write consul gossip encryption key to vault
      hashivault_secret:
        secret: "consul_gossip_key"
        data:
          key: "{{ encryption_key.stdout }}"
        verify: no
        version: 1
        mount_point: "kv"
      when: consul_failure['failed'] == true

    - name: Register Consul Gossip key
      set_fact:
        consul_gossip_key:  "{{ encryption_key.stdout }}" 
      when: consul_failure['failed'] == true

    - name: Register Consul Gossip key
      set_fact:
        consul_gossip_key:  "{{ consul_gossip_key.data.key }}"
      when: consul_failure['failed'] == false

    - name: retrieve Nomad Gossip key from HCP
      set_fact:
        nomad_gossip_key: "{{ lookup('community.hashi_vault.vault_kv1_get', 'nomad_gossip_key') }}"
      ignore_errors: yes
      register: nomad_failure

    - name: Generate a nomad encyption key
      local_action:
        module: command
        cmd: openssl rand -base64 32
      register: encryption_key
      when: nomad_failure['failed'] == true

    - name: write nomad gossip encryption key to vault
      hashivault_secret:
        secret: "nomad_gossip_key"
        data:
          key: "{{ encryption_key.stdout }}"
        verify: no
        version: 1
        mount_point: "kv"
      when: nomad_failure['failed'] == true

    - name: Register Nomad Gossip key
      set_fact:
        nomad_gossip_key:  "{{ encryption_key.stdout }}" 
      when: nomad_failure['failed'] == true

    - name: Register Nomad Gossip key
      set_fact:
        nomad_gossip_key:  "{{ nomad_gossip_key.data.key }}"
      when: nomad_failure['failed'] == false

- name: Assemble Consul cluster
  hosts: consul_instances
  vars:
    consul_raw_key: "{{ hostvars['localhost'].consul_gossip_key }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-consul}

- hosts: localhost
  tasks:
    - name: create aws key
      community.aws.aws_kms:
        alias: vault-enc-key
        enable_key_rotation: true
        tags:
            Name: vault-enc-key
            Purpose: Encrypt S3 containing unseal and root token
        region: eu-west-3
      register: kms_key
      run_once: true
    
- name: Install Vault cluster
  hosts: vault_instances
  vars:
    vault_awskms_key_id: "{{ hostvars['localhost'].kms_key.key_arn }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-vault}

- hosts: localhost
  tasks:
    - name: init Vault
      hashivault_init:
        recovery_shares: 1
        recovery_threshold: 1
        url: "http://{{ groups['vault_instances'][0] }}:8200"
      register: vault_init
      run_once: yes

    - name: Add root token to AWS Secrets Manager
      community.aws.aws_secret:
        name: 'paquerettes_vault_root_token'
        state: present
        secret_type: 'string'
        secret: "{{ vault_init.root_token }}"
        region: eu-west-3
      when: vault_init['changed'] == true

    - name: retrieve root token from AWS Secrets Manager
      set_fact:
        root_token: "{{ lookup('amazon.aws.aws_secret', 'paquerettes_vault_root_token', region='eu-west-3',
   aws_access_key=lookup('env','AWS_ACCESS_KEY'), aws_secret_key=lookup('env','AWS_SECRET_KEY')) }}"

    - name: Create nomad-server policy
      hashivault_policy:
        token: "{{ root_token }}"
        name: nomad-server
        rules_file : nomad-server-policy.hcl
        url: "http://vault.service.consul:8200"

    - name: create nomad-cluster token role
      uri:
        url: http://vault.service.consul:8200/v1/auth/token/roles/nomad-cluster
        method: POST
        body: "{{ lookup('file','nomad-cluster-role.json') }}"
        body_format: json
        status_code: [200, 204]
        headers:
          X-Vault-Token: "{{ root_token }}"

    - name: Create a nomad token
      community.hashi_vault.vault_token_create:
        url: http://vault.service.consul:8200
        policies: ["nomad-server"]
        orphan: true
        period: "72h"
        token: "{{root_token}}"
      register: "nomad_vault_token"

- name: Installing Nomad
  hosts: nomad_instances
  vars:
    nomad_vault_token: "{{ hostvars['localhost'].nomad_vault_token.login.auth.client_token }}"
    nomad_encrypt: "{{ hostvars['localhost'].nomad_gossip_key }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-nomad}
