- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-consul}

- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
      become: true

    - name: create aws key
      community.aws.aws_kms:
        alias: vault-enc-key
        tags:
            Name: vault-enc-key
            Purpose: Encrypt S3 containing unseal and root token
        region: eu-west-3
      register: kms_key
      run_once: true

    - name: Create an empty bucket
      amazon.aws.s3_bucket:
        name: vault-bucket-paquerettes
        state: present
        region: eu-west-3
        acl: private
        delete_public_access: yes
      run_once: true 
    
- name: Install Vault cluster
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-vault}

- hosts: vault_instances
  tasks:
    - name: Copy vault-init binary
      copy:
        src: vault-init
        dest: /usr/bin/vault-init
        owner: vault
        mode : 0744
      become: true
    
    - name: Copy vault-init process file
      copy:
        src: vault-init.service
        dest: /etc/systemd/system/
        mode : 644
      become: true
    
    - name: create vault-init conf dir
      file:
        path: /etc/vault-init
        state: directory
        recurse: yes
        owner: vault
      become: yes
    
    - name: create variable file from template
      template:
        src: variables.j2
        dest: /etc/vault-init/variables
        owner: vault
      become: yes

    - name: call daemon-reload
      systemd:
        daemon_reload: yes
      become: yes
    
    - name: Make sure a vault-init service is running
      systemd:
        state: started
        name: vault-init

- name: Installing Nomad
  hosts: nomad_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-nomad}
