- hosts: localhost
  tasks:
    - name: Ensure python and dependencies are installed
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
      become: true

    - name: Install docker python package
      pip:
        name: '{{ packages }}'
        executable: pip3
      vars:
        packages:
          - boto3
          - hvac
      become: true

    - name: enable transit secret engine
      hashivault_secret_engine:
        name: transit
        state: enabled
        
    - name: create autounseal secret
      community.hashi_vault.vault_write:
        path: transit/keys/autounseal
      register: test

    - name: Create autounseal policy
      hashivault_policy:
        name: autounseal
        rules_file : autounseal.hcl 

    - name: Create a autounseal token
      community.hashi_vault.vault_token_create:
      register: "autounseal_token"

