---
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.hashi_vault
  - name: "git+https://github.com/ansible-community/ansible-vault.git"
    version: 2022.12.01
  - name: "git+https://github.com/ansible-community/ansible-nomad.git"
    version: v3.0.1
  - name: "git+https://github.com/ansible-community/ansible-consul.git"
    version: v1.9.6
