---

- name: Set hostnames
  ansible.builtin.import_tasks: set-hostnames-and-ntp.yml

- name: Bootstrap the global Vault
  ansible.builtin.import_tasks: global-vault-bootstrap.yml

- name: Register CAs
  ansible.builtin.import_tasks: register-ca.yml

- name: Push cert to nodes
  ansible.builtin.import_tasks: push-cert.yml

- name: Assemble consul cluster
  ansible.builtin.import_role:
    name: ansible-consul

- name: Assemble vault cluster
  ansible.builtin.import_role:
    name: ansible-vault

- name: Initialize the global Vault
  ansible.builtin.import_tasks: vault-init.yml

- name: Create and retrieve nomad-server policy token
  ansible.builtin.import_tasks: create-nomad-token.yml

- name: Assemble nomad cluster
  ansible.builtin.import_role:
    name: ansible-nomad

- name: Create and retrieve nomad-server policy token
  ansible.builtin.import_tasks: configure-consul-template.yml
