---

- name: Issue Consul server cert
  hashivault_pki_cert_issue:
    mount_point: hashistack/pki_int_consul
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
    common_name: server.home.consul
    role: consul-home
    extra_params:
      alt_names: "consul.service.consul, consul.service.home.consul"
      ip_sans: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  register: consul_cert
  delegate_to: localhost

- name: Tidy Consul server cert
  hashivault_pki_tidy:
    mount_point: hashistack/pki_int_consul
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
    config:
      safety_buffer: "60s"
      tidy_revoked_certs: true
  run_once: true
  delegate_to: localhost

- name: Write consul ca file to temp dir
  ansible.builtin.copy:
    content: "{{ consul_cert.data.issuing_ca }}"
    dest: /tmp/consul_ca.crt
    mode: '0644'
    force: true

- name: Write consul certificate file to temp dir
  ansible.builtin.copy:
    content: "{{ consul_cert.data.certificate }}"
    dest: /tmp/consul_server.crt
    mode: '0644'
    force: true
  register: consul_cert_changed
  become: true

- name: Write consul private key file to temp dir
  ansible.builtin.copy:
    content: "{{ consul_cert.data.private_key }}"
    dest: /tmp/consul_server.key
    mode: '0600'
    force: true
  become: true

- name: Issue Vault server cert
  hashivault_pki_cert_issue:
    mount_point: hashistack/pki_int_vault
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
    common_name: vault.service.consul
    extra_params:
      ip_sans: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    role: vault-home
  register: vault_cert
  delegate_to: localhost

- name: Tidy Vault server cert
  hashivault_pki_tidy:
    mount_point: hashistack/pki_int_vault
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
    config:
      safety_buffer: "60s"
      tidy_revoked_certs: yes
  run_once: true
  delegate_to: localhost

- name: Write vault ca file to temp dir
  ansible.builtin.copy:
    content: "{{ vault_cert.data.issuing_ca }}"
    dest: /tmp/vault_ca.crt
    mode: '0644'
    force: true

- name: Write vault certificate file to temp dir
  ansible.builtin.copy:
    content: "{{ vault_cert.data.certificate }}"
    dest: /tmp/vault_server.crt
    mode: '0644'
    force: true
  register: vault_cert_changed
  become: true

- name: Write vault private key file to temp dir
  ansible.builtin.copy:
    content: "{{ vault_cert.data.private_key }}"
    dest: /tmp/vault_server.key
    mode: '0600'
    force: true
  become: true

- name: Issue Nomad server cert
  hashivault_pki_cert_issue:
    mount_point: hashistack/pki_int_nomad
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
    common_name: server.global.nomad
    role: nomad-home
    extra_params:
      alt_names: "nomad.service.consul, consul.service.home.consul"
      ip_sans: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  register: nomad_cert
  delegate_to: localhost

- name: Tidy Nomad server cert
  hashivault_pki_tidy:
    mount_point: hashistack/pki_int_nomad
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
    config:
      safety_buffer: "60s"
      tidy_revoked_certs: yes
  run_once: true
  delegate_to: localhost

- name: Write nomad ca file to temp dir
  ansible.builtin.copy:
    content: "{{ nomad_cert.data.issuing_ca }}"
    dest: /tmp/nomad_ca.crt
    mode: '0644'
    force: true

- name: Write nomad certificate file to temp dir
  ansible.builtin.copy:
    content: "{{ nomad_cert.data.certificate }}"
    dest: /tmp/nomad_server.crt
    mode: '0644'
    force: true
  register: nomad_cert_changed
  become: true

- name: Write nomad private key file to temp dir
  ansible.builtin.copy:
    content: "{{ nomad_cert.data.private_key }}"
    dest: /tmp/nomad_server.key
    mode: '0600'
    force: true
  become: true