---

- name: Create ca_certificate dir
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/local
    mode: '0755'
    state: directory

- name: Write root ca file to dir
  ansible.builtin.copy:
    content: "{{ root_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_root_ca.crt
    mode: '0644'
    force: true

- name: Write consul ca file to dir
  ansible.builtin.copy:
    content: "{{ consul_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_consul_ca.crt
    mode: '0644'
    force: true

- name: Write nomad ca file to dir
  ansible.builtin.copy:
    content: "{{ nomad_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_nomad_ca.crt
    mode: '0644'
    force: true

- name: Write vault ca file to dir
  ansible.builtin.copy:
    content: "{{ vault_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_vault_ca.crt
    mode: '0644'
    force: true

- name: Create ca_certificate local dir
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/local
    mode: '0755'
    state: directory
  run_once: true
  delegate_to: localhost

- name: Write root ca file to local dir
  ansible.builtin.copy:
    content: "{{ root_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_root_ca.crt
    mode: '0644'
    force: true
  run_once: true
  delegate_to: localhost

- name: Write consul ca file to local dir
  ansible.builtin.copy:
    content: "{{ consul_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_consul_ca.crt
    mode: '0644'
    force: true
  run_once: true
  delegate_to: localhost

- name: Write nomad ca file to local dir
  ansible.builtin.copy:
    content: "{{ nomad_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_nomad_ca.crt
    mode: '0644'
    force: true
  run_once: true
  delegate_to: localhost

- name: Write vault ca file to local dir
  ansible.builtin.copy:
    content: "{{ vault_ca }}"
    dest: /usr/local/share/ca-certificates/local/home_vault_ca.crt
    mode: '0644'
    force: true
  run_once: true
  delegate_to: localhost

- name: Run dpkg-reconfigure ca-certificate
  ansible.builtin.command: update-ca-certificates
  become: true

- name: Run dpkg-reconfigure ca-certificate local
  ansible.builtin.command: update-ca-certificates
  become: true
  delegate_to: localhost
