---

- name: Set timezone to Europe/Paris
  ansible.builtin.timezone:
    name: Europe/Paris

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostvars[item].node_name }}"
  when: inventory_hostname == item
  with_items: "{{ groups['all'] }}"
  become: true
  notify:
    - reboot server
