---

- name: init Vault
  hashivault_init:
    recovery_shares: 1
    recovery_threshold: 1
    url: "https://{{ groups['instances'][0] }}:8200"
    authtype: token
    token: "{{ global_vault_token }}"
    verify: false
  register: vault_init
  run_once: true
  delegate_to: localhost

- name: Write root token to global vault
  hashivault_secret:
    secret: "vault_root_token"
    data:
      key: "{{ vault_init.root_token }}"
    verify: false
    version: 1
    mount_point: "hashistack/kv"
    url: "{{ global_vault_address }}"
    authtype: token
    token: "{{ global_vault_token }}"
  when: vault_init['changed'] == true
  run_once: true
  delegate_to: localhost

- name: retrieve root token from global vault
  community.hashi_vault.vault_kv1_get:
    engine_mount_point: hashistack/kv
    path: vault_root_token
    url: "{{ global_vault_address }}"
    auth_method: token
    token: "{{ global_vault_token }}"
  ignore_errors: yes
  register: local_vault_token
  run_once: true
  delegate_to: localhost

- name: Sleep for 30s if vault was not initialized
  ansible.builtin.wait_for:
    timeout: 30
  when: vault_init['changed'] == true
  run_once: true
  delegate_to: localhost