---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  listen: "reload systemd"

- name: Restart consul-template service
  ansible.builtin.systemd:
    name: consul-template
    state: restarted
  become: true
  listen: "restart consul-template service"

- name: Restart nomad-template service
  ansible.builtin.systemd:
    name: nomad-template
    state: restarted
  become: true
  listen: "restart nomad-template service"

- name: Restart nomad-template service
  ansible.builtin.systemd:
    name: vault-template
    state: restarted
  become: true
  listen: "restart vault-template service"

- name: Reboot server
  ansible.builtin.reboot:
  become: true
