---
# This section is not needed if you use the docker image
#
#- hosts: localhost
#  tasks:
#    - name: Ensure dependencies are installed on localhost
#      apt:
#        name: '{{ packages }}'
#      vars:
#        packages:
#          - python3
#          - python3-pip
#          - python3-setuptools
#          - python3-virtualenv
#      become: true
#
#    - name: Ensure python libraries are installed on localhost
#      pip:
#        name: '{{ packages }}'
#        executable: pip3
#      vars:
#        packages:
#          - hvac
#      become: true

- name: Assemble Hashistack cluster
  hosts: instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible_hashistack}
